name: Java tests

on:
    push:
        branches:
            - master
    pull_request:
        types:
            - opened
            - ready_for_review
            - edited
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'oracle'
            - name: Test with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: test